### ISSUE TITLE
Detecting if it's an html document by checking header with external lib is not really bullet proof

### ISSUE THREAD

**Issue by atrhacker** [bda-research/node-crawler#193] opened 2017-01-26 14:28 UTC
Hey guys,

I really love your library and you do great work. 
Thanks for this!
I'm happy that you switched back to the original repository and still maintain it. Because it's very useful.

I'm using your library to crawl lots of stuff, and since approximatively two months, I noticed that for some links,  jquery was not injected in the response.

After some digging, I noticed that you changed a bit the way your determined if a content is html or not
`   if (!options.html && !typeis(contentType(response), ['html'])){
	log("warn","response body is not HTML, skip injecting");
	return options.callback(null,response,options.release);
    }`

My main concern is that it's not always working.
For example, If you try to crawl this link with your crawler
http://www.npr.org/sections/thetwo-way/2017/01/26/511756505/14-years-later-venus-and-serena-williams-meet-again-in-australian-open-final

Jquery will not be injected because `typeis(contentType(response), ['html'])` will return false.

Why ? Because the headers sent back by the server are the following
`Content-Type:text/html;;charset=UTF-8`

So its looks normal header no ?
As you can see  there is an extra ; in the headers and the website is a big news website in the US.
And they are so many websites which the headers sent back can have typo misformation, etc...

My point is that, it's only an example, but it seems that this external library you are using to determine the content type of a response seems not to be optimum.

However I agree, I don't know what would be the way to have the best way to detect if a response is html or not.
The solution used previoulsy with a good old regex was not optimum I agree but maybe we could improve it ?

Old code:
`var isHTML = _.isString(response.body) && response.body.match(/^\s*</);`

Thanks again, and I'm very curious to read your opinion on this,

Anselme

**Comment by mike442144** [comment] 2017-02-07 03:12
Thanks, as you said, it was a typo in `Content-Type`. We just remove the old code to follow the standard http protocol. see [RFC7231](https://tools.ietf.org/html/rfc7231#section-3.1.1.5).

I suggest you to open a new issue on typeis project and link to this issue. Maybe the author of typeis has some suggestions.

Or do you have any other ways to solve it?

**Comment by mike442144** [comment] 2018-05-31 03:11
We have opened an issue in `type-is` project and the author [said](https://github.com/jshttp/type-is/issues/34) that was intended too. So let's do some preprocess work before `type-is`.

**Comment by mike442144** [comment] 2018-05-31 12:10
Fixed in v1.1.4

**Closed by mike442144** 2018-05-31 12:10 UTC
Labels: Optimization
