### ISSUE TITLE
How to set request headers?

### ISSUE THREAD

**Issue by shen-lan** [bda-research/node-crawler#306] opened 2019-03-26 02:33 UTC
I tried to 
```
    preRequest: function(options,done) {
        // console.log(options);
        options.userAgent = 'xxx';
        done()
    },
```
but failed:
```
    callback : function (error, res, done) {
        if(error){
            console.log(error);
        }else{
              console.log(res.options.userAgent)   //undefined 
        }
   }
```

**Comment by mike442144** [comment] 2019-04-02 05:54
Hey guy, please read the document, the issue is not supposed to answer questions, we use it to report bugs, request features etc. so I'm closing the issue. 

BTW, you can customize http header by adding `headers` key to options which should be an plain Object

**Closed by mike442144** 2019-04-02 05:54 UTC
